feat: adding annotations for services.yaml
rm3l/helm-charts pull request #69
Opened 2024-06-08 19:47 UTC by fwmarcel

added the option to add annotations to services to fix #67

2024-06-08 21:19 UTC, rm3l requested changes
@fwmarcel Thank you for this contribution! I've added a few comments.
Also, please consider bumping the Chart version to fix the Lint CI job: https://github.com/rm3l/helm-charts/actions/runs/9431312497/job/25980284181?pr=69#step:9:31

2024-06-08 21:19 UTC, rm3l commented on charts/adguard-home/templates/deployment.yaml
> +          claimName: {{ .Values.persistence.existingVolumeClaim | default (include "adguard-home.fullname" .) }}
+1 for this feature, but this seems not relevant to this PR. Can you please create a separate PR for this, for a better separation of concern?

2024-06-08 21:19 UTC, rm3l commented on charts/adguard-home/templates/persistentvolumeclaim.yaml
> +{{- if not .Values.persistence.existingVolumeClaim }}
See my previous comment. I'd suggest creating a separate PR for this.

2024-06-08 21:19 UTC, rm3l commented on charts/adguard-home/templates/services.yaml
Can you please add a new test values file under the [`charts/adguard-home/ci`](https://github.com/rm3l/helm-charts/tree/main/charts/adguard-home/ci) folder? This is to have it tested in CI. You can put anything as services annotations. Thanks.

2024-06-09 11:33 UTC, fwmarcel commented on charts/adguard-home/templates/deployment.yaml
> +          claimName: {{ .Values.persistence.existingVolumeClaim | default (include "adguard-home.fullname" .) }}
This shouldn't really be in the pr

2024-06-09 11:39 UTC, fwmarcel commented on charts/adguard-home/templates/services.yaml
test values are added.

2024-06-09 21:02 UTC, rm3l requested changes

2024-06-09 21:02 UTC, rm3l commented on charts/adguard-home/ci/with-service-annotations.yaml
Thanks for adding this file. I didn't see it detected in CI (https://github.com/rm3l/helm-charts/actions/runs/9439247205/job/25997267519?pr=69), then remembered that the filename needs to matching the glob pattern `*-values.yaml`, otherwise it will be ignored. See https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md#synopsis.
Could you please rename it accordingly? Thanks.

2024-06-12 16:17 UTC, rm3l commented on charts/adguard-home/ci/with-service-annotations.yaml
@fwmarcel FYI ;)

2024-06-15 08:10 UTC, merged

2024-06-15 08:10 UTC, rm3l reviewed
Thanks for your patience and contribution, @fwmarcel !!!