feat: Add option to configure externalTrafficPolicy
rm3l/helm-charts pull request #75
Opened 2024-06-15 10:39 UTC by m-wrzesien

Resolves #72

2024-06-15 19:59 UTC, rm3l requested changes
Thanks for this PR. Added a few comments, mostly typos.
Also, can you add a simple test values file (under the [ci](https://github.com/rm3l/helm-charts/tree/main/charts/adguard-home/ci) directory) setting this field in all services? This way, we can get it tested. Thanks.

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-15 19:59 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalacer" or "NodePort"
```suggestion
    # -- Set traffic policy for external traffic. Set to "Local" to preserve client ip address in case of service type "LoadBalancer" or "NodePort"
```

2024-06-16 06:12 UTC, m-wrzesien commented
Sure, I've added 2 more commits which should fix typos and add those test values

2024-06-16 13:47 UTC, rm3l approved these changes
Thanks!!

2024-06-16 14:05 UTC, merged