Fix and improve adguard home helm chart
rm3l/helm-charts pull request #77
Opened 2024-08-01 00:40 UTC by titilambert

This PR is about adguard home helm chart and:
* Dixes the port definitions of the deployment
* Add priorityClassName support
* Put all the probes definitions into the values.yaml
* Add existingClaim support

Thanks for doing this helm chart !

2024-08-01 01:09 UTC, titilambert commented
It also removes the useless 3000 TCP port and service and ingress

2024-08-20 22:25 UTC, rm3l requested changes
Thanks for this PR! CI seems to be failing because this Chart needs a version bump: https://github.com/rm3l/helm-charts/pull/77/checks#step:9:31

Could you bump the Chart version please? See https://github.com/rm3l/helm-charts/blob/main/charts/adguard-home/Chart.yaml#L21
Thanks.

2024-08-27 20:52 UTC, fwmarcel commented
@rm3l i wait for this fix. the current version breaks the dns service.

2024-08-27 22:57 UTC, rm3l approved these changes

2024-08-27 23:02 UTC, merged