Add support storageClass for volumeClaim
rm3l/helm-charts pull request #78
Opened 2024-08-18 13:55 UTC by belaytzev

2024-08-20 22:26 UTC, rm3l requested changes
Thanks for this PR! CI seems to be failing because this Chart needs a version bump: https://github.com/rm3l/helm-charts/actions/runs/10441188373/job/28956921606?pr=78#step:9:31

Could you bump the Chart version please? See https://github.com/rm3l/helm-charts/blob/main/charts/adguard-home/Chart.yaml#L21
Thanks.

2024-08-22 07:55 UTC, rm3l requested changes

2024-08-22 07:55 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    storageClassName: ""
```suggestion
    storageClassName: null
```

I think that in order for the PVC to use the default storage class by default, the `storageClassName` property needs to be omitted or set to `null` in the PVC spec.
Otherwise, the PVC will remain stuck in the Pending state.

```
$ helm upgrade --install agh charts/adguard-home                                                                    
Release "agh" does not exist. Installing it now.
NAME: agh
LAST DEPLOYED: Thu Aug 22 09:45:53 2024
NAMESPACE: my-ns
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace my-ns -l "app.kubernetes.io/name=adguard-home,app.kubernetes.io/instance=agh" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace my-ns $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace my-ns port-forward $POD_NAME 8080:$CONTAINER_PORT

$ kubectl get pvc -w
NAME               STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
agh-adguard-home   Pending                                                     97s
```

2024-08-22 07:56 UTC, rm3l commented on charts/adguard-home/values.yaml
> +    storageClassName: ""
We can notice that CI is failing for this reason - see https://github.com/rm3l/helm-charts/actions/runs/10502579083/job/29097676785?pr=78#step:11:138

2024-08-22 08:15 UTC, belaytzev commented on charts/adguard-home/values.yaml
> +    storageClassName: ""
Yes, you are right. It looks better to omit this in default values.

2024-08-22 08:15 UTC, closed without merging